---
title: "CSP571 Summer 2022 Project. Gap Phenomenon in Stock Market: Evaluating the Significance of Price Gaps in Predicting Future Returns Using Statistical and Machine Learning Techniques"
output: 
  html_notebook: 
    toc: yes
    toc_float: yes
    toc_depth: 6
author: Oleksandr Shashkov and Santosh Chaluvaraju
        Illinois Institute of Technology
---

## SANTOSH CODE TO prepare dictionary (Please change the csv path)
```{r}
rm(list = ls())
```

```{r}
getList <- function(str, delimiter)
{
  return (unique(unlist(strsplit(str,delimiter))))
}
```

```{r}
df <- read.csv("/home/santosh/Desktop/MASTERS/STUDIES_MSDS/SEM_2_summer/Data_preparation_and_analysis/PROJECT/git_work/Gap-Phenomenon-in-Stock-Market/S&P 500 Historical Components & Changes(03-14-2022).csv")

#list of ticker list
listOfTkrList<- list()
for (x in 1:2648) {
  #getting ticker list of each row i.e. for a particular date 
    listOfTkrList[[x]] <- getList(df[x,2], ",")
}
#creating ticker period dictionary
tkrperiodDict <- dict()
x <- 1

#Iterating over list of ticker list
for (tkrList in listOfTkrList) {
  #Date of row x
  startDate <- df[x,1]
  
  #Iterating over each ticker in each list
  for (tkr in listOfTkrList[[x]]) {
    y <- x + 1
    #Iterating over each list after "tkrList" in list of lists i.e. listOfTkrList
    for (i in y:2648) {
      if(tkr %in% listOfTkrList[[i]]){
        index = which(listOfTkrList[[i]] == tkr)
        listOfTkrList[[i]] <- listOfTkrList[[i]][-index]
        endDate = df[i,1]
      }else{
        #If dictionary already has the key append the list
        if(tkrperiodDict$has(tkr)){
          periodList <- tkrperiodDict$get(tkr)
          tkrperiodDict$set(tkr, append(periodList, list(list(startDate, endDate))))
        }
        # ELSE make a new entry
        else{
          tkrperiodDict$set(tkr, list(list(startDate, endDate)))
        }
        break
      }
    }
    
  }
  
  x <- x + 1
  if(x == 2648){
    break
  }
  
}

```
```{r}
print(tkrperiodDict$get("AAL"))
```
## END SANtOSH CODE

# 1. Removing Survival Bias

```{r}
library(collections)
```
```{r}
# mock up dictionary using list of lists to emulate ticker-ranges pairs
tickers <- c("AAL","AAMRQ","AAPL")
AAL1 <- list(as.Date("1/2/1996","%m/%d/%Y"),as.Date("1/13/1997","%m/%d/%Y"))
AAL2 <- list(as.Date("3/23/2015","%m/%d/%Y"),as.Date("3/2/2022","%m/%d/%Y"))
AAL <- list(AAL1,AAL2)
AAMRQ <- list(list(as.Date("1/2/1996","%m/%d/%Y"),as.Date("3/10/2003","%m/%d/%Y")))
AAPL <- list(list(as.Date("1/2/1996","%m/%d/%Y"),as.Date("3/2/2022","%m/%d/%Y")))
ranges <- list(AAL,AAMRQ,AAPL)
sp500_composition <- dict(items = ranges, keys = tickers)
rm(AAL,AAL1,AAL2,AAMRQ,AAPL,ranges,tickers)
```

```{r}
# load the S&P500 historical composition
SnP_components_raw <- read.csv(file=file.choose())
```
```{r}
# form a set of all stocks tickers
tickers_set <- c()
for (composition in SnP_components_raw$tickers) {
  curr_composition <- strsplit(composition,split = ",")
  tickers_set <- unique(c(tickers_set,curr_composition[[1]]))
}
```
```{r}
for (tcr in tickers_set) {
  listed <- FALSE
  #print(tcr)
  # todo: declare start time stamp variable
  for (i in 1:nrow(SnP_components_raw)) {
    timestep <- SnP_components_raw[i,]
    curr_timestamp <- timestep$date[[1]][1]

    
    
    if (!(tcr %in% strsplit(timestep$tickers,split = ",")[[1]])){
      # ticker not in the composition
      if (listed){# stock was listed but now it is not
        # todo: form an entry in the list containing start and stop time stamps
        listed = FALSE
        
      }


    } else {# ticker is in the current composition
      
      if (!listed){# stock was not listed previously
        listed = TRUE
        # todo: update start range time stamp
      }
      # todo: update last seen time stamp
      
      
    }
    
    
  }
  # update global dictionary
  
}

```


```{r}
# mock up of processing dicitonary to download stocks data for the ranges
for (stock in sp500_composition$keys()) {
  for (rng in sp500_composition$get(stock)){
    cat("ticker:",stock,"start:",
        format.Date(rng[[1]][1]),
        "stop:",format.Date(rng[[2]][1]),"\n")
    # todo: download stocks data here having ticker and time stamps


  }
  
}
```